[package]
name = "counter_program"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = { path = "../../../program" }
borsh = { version = "1.5.1", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[workspace]